name = input('What is your name? ')
colour = input('What is your favourite colour? ')
age = input('What is your age? ')
bigAge = int(age)
print(type(bigAge))
print(name + ' likes ' + colour + ' ' + bigAge)
